# Generated by Django 3.0.8 on 2020-09-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('item_url', models.TextField(unique=True)),
                ('item_price', models.TextField(unique=True)),
                ('post_date', models.DateTimeField()),
                ('jan_code', models.TextField()),
                ('recommended_word', models.TextField()),
                ('asin_code', models.TextField()),
                ('asin_name', models.TextField()),
                ('asin_price', models.TextField()),
                ('yahoo_shop', models.TextField()),
                ('yahoo_name', models.TextField()),
                ('yahoo_url', models.TextField()),
                ('yahoo_price', models.TextField()),
                ('yahoo_stock', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('item_url', models.TextField(unique=True)),
                ('item_price', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('artist', models.TextField()),
                ('director', models.TextField()),
                ('related_works', models.TextField()),
                ('selling_agency', models.TextField()),
                ('distributor', models.TextField()),
                ('number_of_disks', models.TextField()),
                ('duration', models.TextField()),
                ('bonus_video', models.TextField()),
                ('manufacturer_part_number', models.TextField()),
                ('jan_code', models.TextField()),
                ('in_store_code', models.TextField()),
                ('set_content', models.TextField()),
                ('asin_code', models.TextField()),
                ('asin_name', models.TextField()),
                ('asin_price', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('item_url', models.TextField(unique=True)),
                ('shop_name', models.TextField()),
                ('item_price', models.TextField()),
                ('jan_code', models.TextField()),
                ('asin_code', models.TextField()),
            ],
        ),
    ]
