# Generated by Django 3.0.8 on 2020-08-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('item_url', models.TextField(unique=True)),
                ('post_date', models.DateTimeField()),
            ],
        ),
    ]
