# Generated by Django 3.0.8 on 2020-09-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gei',
            name='asin_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
