# Generated by Django 3.0.8 on 2020-08-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dona', '0002_gei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('item_url', models.TextField(unique=True)),
                ('shop_name', models.TextField()),
                ('item_price', models.TextField()),
                ('jan_code', models.TextField()),
            ],
        ),
    ]
